// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://my-gpi.io/terms/",
        "contact": {
            "name": "Endy Apinageri",
            "url": "https://www.endyapina.com",
            "email": "endy.apinageri@my-gpi.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/apicore/authentication/login": {
            "post": {
                "description": "Send user data to the main authentication login endpoint endpoint.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authorization"
                ],
                "summary": "Endpoint to send user data for login",
                "parameters": [
                    {
                        "description": "The User Login data",
                        "name": "LoginData",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.LoginData"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "User Registration default data",
                        "schema": {
                            "$ref": "#/definitions/controller.LoginObject"
                        }
                    },
                    "400": {
                        "description": "API response object",
                        "schema": {
                            "$ref": "#/definitions/controller.ResponseObject"
                        }
                    }
                }
            }
        },
        "/apicore/authentication/pasword/change": {
            "post": {
                "description": "When a user decides to change password, frontend call api with old and new password",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authorization"
                ],
                "summary": "Change password updates a user password with a current one",
                "parameters": [
                    {
                        "description": "The new password changes",
                        "name": "ChangePassword",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.ChangePassword"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Check email for password mail and link",
                        "schema": {
                            "$ref": "#/definitions/controller.ResponseObject"
                        }
                    },
                    "400": {
                        "description": "API response object",
                        "schema": {
                            "$ref": "#/definitions/controller.ResponseObject"
                        }
                    }
                }
            }
        },
        "/apicore/authentication/pasword/forget": {
            "post": {
                "description": "When a user forgets password, forgetPassword endpoint handles sending a new link for password recovery",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authorization"
                ],
                "summary": "Endpoint to request for new user password",
                "parameters": [
                    {
                        "description": "The user email",
                        "name": "string",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Check email for password mail and link",
                        "schema": {
                            "$ref": "#/definitions/controller.ResponseObject"
                        }
                    },
                    "400": {
                        "description": "API response object",
                        "schema": {
                            "$ref": "#/definitions/controller.ResponseObject"
                        }
                    }
                }
            }
        },
        "/apicore/authentication/registration": {
            "post": {
                "description": "Send user data to the main authentication endpoint.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authorization"
                ],
                "summary": "Endpoint to send user data for registration",
                "parameters": [
                    {
                        "description": "The User Registration data",
                        "name": "RegistrationData",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.RegistrationData"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "User Registration default data",
                        "schema": {
                            "$ref": "#/definitions/controller.UserData"
                        }
                    },
                    "400": {
                        "description": "API response object",
                        "schema": {
                            "$ref": "#/definitions/controller.ResponseObject"
                        }
                    }
                }
            }
        },
        "/apicore/authentication/registration/verify": {
            "post": {
                "description": "Send user data and verification code to verify validity of verification.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authorization"
                ],
                "summary": "Endpoint to verify user registration link",
                "parameters": [
                    {
                        "description": "The User Registration data and code",
                        "name": "RegistrationData",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.VerifyRegistration"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "User Registration default data",
                        "schema": {
                            "$ref": "#/definitions/controller.RegistrationObject"
                        }
                    },
                    "400": {
                        "description": "API response object",
                        "schema": {
                            "$ref": "#/definitions/controller.ResponseObject"
                        }
                    }
                }
            }
        },
        "/apicore/business/": {
            "post": {
                "description": "Send user data to the main authentication endpoint.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "APICORE Business"
                ],
                "summary": "Endpoint to send user data for registration",
                "parameters": [
                    {
                        "description": "The Business Registration Data",
                        "name": "BusinessRegistration",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.BusinessRegistration"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success data ",
                        "schema": {
                            "$ref": "#/definitions/controller.BusinessProfile"
                        }
                    },
                    "400": {
                        "description": "API response object",
                        "schema": {
                            "$ref": "#/definitions/controller.ResponseObject"
                        }
                    }
                }
            },
            "delete": {
                "description": "Perform Delete endpoint for Business Registration",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "APICORE Business"
                ],
                "summary": "Endpoint to delete a user business information",
                "parameters": [
                    {
                        "description": "The Business Registration Data",
                        "name": "BusinessProfile",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.BusinessProfile"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success data ",
                        "schema": {
                            "$ref": "#/definitions/controller.BusinessProfile"
                        }
                    },
                    "400": {
                        "description": "API response object",
                        "schema": {
                            "$ref": "#/definitions/controller.ResponseObject"
                        }
                    }
                }
            }
        },
        "/apicore/business/all": {
            "get": {
                "description": "Get an array of all business and business data",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "APICORE Business"
                ],
                "summary": "Endpoint to get all businesses on BARAFIRI",
                "responses": {
                    "200": {
                        "description": "Success data ",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/controller.BusinessResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "API response object",
                        "schema": {
                            "$ref": "#/definitions/controller.ResponseObject"
                        }
                    }
                }
            }
        },
        "/apicore/business/update": {
            "post": {
                "description": "Perform Update endpoint for Business Registration",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "APICORE Business"
                ],
                "summary": "Endpoint to update user business data",
                "parameters": [
                    {
                        "description": "The Business Registration Data",
                        "name": "BusinessProfile",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.BusinessProfile"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success data ",
                        "schema": {
                            "$ref": "#/definitions/controller.BusinessProfile"
                        }
                    },
                    "400": {
                        "description": "API response object",
                        "schema": {
                            "$ref": "#/definitions/controller.ResponseObject"
                        }
                    }
                }
            }
        },
        "/apicore/business/{buid}": {
            "get": {
                "description": "Get an array of all business and business data by business unique ids",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "APICORE Business"
                ],
                "summary": "Endpoint to get business information by id",
                "parameters": [
                    {
                        "description": "The Business unique id string",
                        "name": "businessid",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success data ",
                        "schema": {
                            "$ref": "#/definitions/controller.BusinessResponse"
                        }
                    },
                    "400": {
                        "description": "API response object",
                        "schema": {
                            "$ref": "#/definitions/controller.ResponseObject"
                        }
                    }
                }
            }
        },
        "/apicore/token/reset": {
            "get": {
                "description": "Pass token in the Authorization header. Verify the token and send a new one with updated credentials",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authorization"
                ],
                "summary": "Reset token renews old token string",
                "responses": {
                    "200": {
                        "description": "Check validity",
                        "schema": {
                            "$ref": "#/definitions/controller.VerifyToken"
                        }
                    },
                    "400": {
                        "description": "API response object",
                        "schema": {
                            "$ref": "#/definitions/controller.ResponseObject"
                        }
                    }
                }
            }
        },
        "/apicore/token/user": {
            "get": {
                "description": "Pass token in the Authorization header. Verify token checks if the token is verified and send the authenticated user application related data",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authorization"
                ],
                "summary": "Checks if an authenticated user token is valid, and send user data of authenticated user",
                "responses": {
                    "200": {
                        "description": "Check validity",
                        "schema": {
                            "$ref": "#/definitions/controller.LoginObject"
                        }
                    },
                    "400": {
                        "description": "API response object",
                        "schema": {
                            "$ref": "#/definitions/controller.ResponseObject"
                        }
                    }
                }
            }
        },
        "/apicore/token/verify": {
            "get": {
                "description": "Pass token in the Authorization header. Verify token checks if the token is verified",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authorization"
                ],
                "summary": "Checks if an authenticated user token is valid.",
                "responses": {
                    "200": {
                        "description": "Check validity",
                        "schema": {
                            "$ref": "#/definitions/controller.VerifyToken"
                        }
                    },
                    "400": {
                        "description": "API response object",
                        "schema": {
                            "$ref": "#/definitions/controller.ResponseObject"
                        }
                    }
                }
            }
        },
        "/apicore/user/": {
            "patch": {
                "description": "Update user data. This happens when a user wants to update user information",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authorization"
                ],
                "summary": "Update user information",
                "parameters": [
                    {
                        "description": "Update user data json object",
                        "name": "UserData",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.UserData"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "User related data",
                        "schema": {
                            "$ref": "#/definitions/controller.UserData"
                        }
                    },
                    "400": {
                        "description": "API response object",
                        "schema": {
                            "$ref": "#/definitions/controller.ResponseObject"
                        }
                    }
                }
            }
        },
        "/apicore/user/{uid}": {
            "get": {
                "description": "Get user uid from url and retrieve user data with the uid string",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authorization"
                ],
                "summary": "Retrieve user data from user id",
                "responses": {
                    "200": {
                        "description": "User related data",
                        "schema": {
                            "$ref": "#/definitions/controller.UserData"
                        }
                    },
                    "400": {
                        "description": "API response object",
                        "schema": {
                            "$ref": "#/definitions/controller.ResponseObject"
                        }
                    }
                }
            }
        },
        "/business/{buid}/order/all": {
            "get": {
                "description": "Get orders for a particular business",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sales"
                ],
                "summary": "Endpoint to get all business orders",
                "responses": {
                    "200": {
                        "description": "Success data. Check response body for data containing business data and all product array",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/controller.OrderResponseBody"
                            }
                        }
                    },
                    "400": {
                        "description": "API response object",
                        "schema": {
                            "$ref": "#/definitions/controller.ResponseObject"
                        }
                    }
                }
            }
        },
        "/business/{buid}/order/{orderid}": {
            "get": {
                "description": "Get order for a particular business",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sales"
                ],
                "summary": "Endpoint to get a business order",
                "responses": {
                    "200": {
                        "description": "Success data. Check response body for data containing business data and all product array",
                        "schema": {
                            "$ref": "#/definitions/controller.OrderResponseBody"
                        }
                    },
                    "400": {
                        "description": "API response object",
                        "schema": {
                            "$ref": "#/definitions/controller.ResponseObject"
                        }
                    }
                }
            }
        },
        "/business/{buid}/order/{orderid}/cancel": {
            "patch": {
                "description": "Businesses can reject or cancel a user order of their endpoint. Frontend can call this API for that purpose",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sales"
                ],
                "summary": "Endpoint to cancel or reject a user order",
                "parameters": [
                    {
                        "description": "The Product order data",
                        "name": "CreateOrder",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.CreateOrder"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Order response body",
                        "schema": {
                            "$ref": "#/definitions/controller.OrderResponseBody"
                        }
                    },
                    "400": {
                        "description": "API response object",
                        "schema": {
                            "$ref": "#/definitions/controller.ResponseObject"
                        }
                    }
                }
            }
        },
        "/cart/add": {
            "post": {
                "description": "Add new product information to cart system",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User Cart"
                ],
                "summary": "Endpoint to add new product to user cart information",
                "parameters": [
                    {
                        "description": "The product data in the cart, as well as the user information",
                        "name": "Cart",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.Cart"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success cart data",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/controller.Cart"
                            }
                        }
                    },
                    "400": {
                        "description": "API response object",
                        "schema": {
                            "$ref": "#/definitions/controller.ResponseObject"
                        }
                    }
                }
            }
        },
        "/cart/empty": {
            "delete": {
                "description": "This is used when a user wants to empty user cart",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User Cart"
                ],
                "summary": "Endpoint to remove all product from cart item",
                "parameters": [
                    {
                        "description": "The product data in the cart, as well as the user information",
                        "name": "Cart",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.Cart"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success data ",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/controller.Cart"
                            }
                        }
                    },
                    "400": {
                        "description": "API response object",
                        "schema": {
                            "$ref": "#/definitions/controller.ResponseObject"
                        }
                    }
                }
            }
        },
        "/cart/remove/{productid}": {
            "delete": {
                "description": "This is used when a user wants to remove a particular data from cart",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User Cart"
                ],
                "summary": "Endpoint to remove product from cart item",
                "parameters": [
                    {
                        "description": "The product data in the cart, as well as the user information",
                        "name": "Cart",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.Cart"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success data ",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/controller.Cart"
                            }
                        }
                    },
                    "400": {
                        "description": "API response object",
                        "schema": {
                            "$ref": "#/definitions/controller.ResponseObject"
                        }
                    }
                }
            }
        },
        "/payments/transaction/pay": {
            "post": {
                "description": "Endpoint to create new transaction for businesses.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Public API"
                ],
                "summary": "Endpoint to create new transaction for businesses",
                "parameters": [
                    {
                        "description": "The payment data",
                        "name": "Pay",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.Pay"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success data. Check response body for data",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/controller.ProductResponseObject"
                            }
                        }
                    },
                    "400": {
                        "description": "API response object",
                        "schema": {
                            "$ref": "#/definitions/controller.ResponseObject"
                        }
                    }
                }
            }
        },
        "/products/store/": {
            "post": {
                "description": "Add products information to store. This makes the product visible to all users",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Product Store"
                ],
                "summary": "Add product to store create new product appended to the store",
                "parameters": [
                    {
                        "description": "The Product data to be stored",
                        "name": "Products",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.Products"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "The product data",
                        "schema": {
                            "$ref": "#/definitions/controller.Products"
                        }
                    },
                    "400": {
                        "description": "API response object",
                        "schema": {
                            "$ref": "#/definitions/controller.ResponseObject"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete product information of the store",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Product Store"
                ],
                "summary": "Delete product information of the store",
                "parameters": [
                    {
                        "description": "The Product data to be stored",
                        "name": "Products",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.Products"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "The product data",
                        "schema": {
                            "$ref": "#/definitions/controller.Products"
                        }
                    },
                    "400": {
                        "description": "API response object",
                        "schema": {
                            "$ref": "#/definitions/controller.ResponseObject"
                        }
                    }
                }
            },
            "patch": {
                "description": "Update product store edits some store data",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Product Store"
                ],
                "summary": "Update product information of the store",
                "parameters": [
                    {
                        "description": "The Product data to be stored",
                        "name": "Products",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.Products"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "The product data",
                        "schema": {
                            "$ref": "#/definitions/controller.Products"
                        }
                    },
                    "400": {
                        "description": "API response object",
                        "schema": {
                            "$ref": "#/definitions/controller.ResponseObject"
                        }
                    }
                }
            }
        },
        "/products/store/{buid}": {
            "get": {
                "description": "Get all product information about a business from business unique id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Product Store"
                ],
                "summary": "This endpoint retrieves all product data belonging to the business",
                "responses": {
                    "200": {
                        "description": "The product data",
                        "schema": {
                            "$ref": "#/definitions/controller.UserData"
                        }
                    },
                    "400": {
                        "description": "API response object",
                        "schema": {
                            "$ref": "#/definitions/controller.ResponseObject"
                        }
                    }
                }
            }
        },
        "/public/business/products/all": {
            "get": {
                "description": "Get business information and products",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Public API"
                ],
                "summary": "Endpoint to get business information based on business unique id",
                "responses": {
                    "200": {
                        "description": "Success data. Check response body for data containing business data and all product array",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/controller.BusinessResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "API response object",
                        "schema": {
                            "$ref": "#/definitions/controller.ResponseObject"
                        }
                    }
                }
            }
        },
        "/public/product/all": {
            "get": {
                "description": "Get an array of all business and business data",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Public API"
                ],
                "summary": "Endpoint to get all product information on BARAFIRI",
                "responses": {
                    "200": {
                        "description": "Success data. Check response body for data",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/controller.ProductResponseObject"
                            }
                        }
                    },
                    "400": {
                        "description": "API response object",
                        "schema": {
                            "$ref": "#/definitions/controller.ResponseObject"
                        }
                    }
                }
            }
        },
        "/public/product/{puid}": {
            "get": {
                "description": "Get product by product id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Public API"
                ],
                "summary": "Endpoint to get all product information on BARAFIRI",
                "responses": {
                    "200": {
                        "description": "Success data. Check response body for data",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/controller.ProductResponseObject"
                            }
                        }
                    },
                    "400": {
                        "description": "API response object",
                        "schema": {
                            "$ref": "#/definitions/controller.ResponseObject"
                        }
                    }
                }
            }
        },
        "/search/products/category/{text}": {
            "get": {
                "description": "Search the system for products match and category match",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Public Search"
                ],
                "summary": "Endpoint to search the system database for text matches in products and category",
                "responses": {
                    "200": {
                        "description": "Success search result from the procuts section",
                        "schema": {
                            "$ref": "#/definitions/controller.SearchResult"
                        }
                    },
                    "400": {
                        "description": "API response object",
                        "schema": {
                            "$ref": "#/definitions/controller.ResponseObject"
                        }
                    }
                }
            }
        },
        "/search/products/industry/{text}": {
            "get": {
                "description": "Search the system for products match and industry match",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Public Search"
                ],
                "summary": "Endpoint to search the system database for text matches in products and industry",
                "responses": {
                    "200": {
                        "description": "Success search result from the procuts section",
                        "schema": {
                            "$ref": "#/definitions/controller.SearchResult"
                        }
                    },
                    "400": {
                        "description": "API response object",
                        "schema": {
                            "$ref": "#/definitions/controller.ResponseObject"
                        }
                    }
                }
            }
        },
        "/search/products/price/{minprice}/{maxprice}": {
            "get": {
                "description": "Search the system for products match and price range match",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Public Search"
                ],
                "summary": "Endpoint to search the system database for text matches in products and match in prices",
                "responses": {
                    "200": {
                        "description": "Success search result from the procuts section",
                        "schema": {
                            "$ref": "#/definitions/controller.SearchResult"
                        }
                    },
                    "400": {
                        "description": "API response object",
                        "schema": {
                            "$ref": "#/definitions/controller.ResponseObject"
                        }
                    }
                }
            }
        },
        "/search/products/{text}": {
            "get": {
                "description": "Search the system for products match",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Public Search"
                ],
                "summary": "Endpoint to search the system database for text matches in products",
                "responses": {
                    "200": {
                        "description": "Success search result from the procuts section",
                        "schema": {
                            "$ref": "#/definitions/controller.SearchResult"
                        }
                    },
                    "400": {
                        "description": "API response object",
                        "schema": {
                            "$ref": "#/definitions/controller.ResponseObject"
                        }
                    }
                }
            }
        },
        "/search/{text}": {
            "get": {
                "description": "Search the system for products and data match",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Public Search"
                ],
                "summary": "Endpoint to search the system database for text matches in products and services",
                "responses": {
                    "200": {
                        "description": "Success search result ",
                        "schema": {
                            "$ref": "#/definitions/controller.SearchResult"
                        }
                    },
                    "400": {
                        "description": "API response object",
                        "schema": {
                            "$ref": "#/definitions/controller.ResponseObject"
                        }
                    }
                }
            }
        },
        "/user/order/": {
            "post": {
                "description": "Send create order data to order for a new product.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sales"
                ],
                "summary": "Endpoint to create a new user order",
                "parameters": [
                    {
                        "description": "The Product order data",
                        "name": "CreateProductOrder",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.CreateProductOrder"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Order response body",
                        "schema": {
                            "$ref": "#/definitions/controller.OrderResponseBody"
                        }
                    },
                    "400": {
                        "description": "API response object",
                        "schema": {
                            "$ref": "#/definitions/controller.ResponseObject"
                        }
                    }
                }
            }
        },
        "/user/order/all": {
            "get": {
                "description": "Get business information and products",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sales"
                ],
                "summary": "Endpoint to get all orders of an individual user",
                "responses": {
                    "200": {
                        "description": "Success data. Check response body for data containing business data and all product array",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/controller.OrderResponseBody"
                            }
                        }
                    },
                    "400": {
                        "description": "API response object",
                        "schema": {
                            "$ref": "#/definitions/controller.ResponseObject"
                        }
                    }
                }
            }
        },
        "/user/order/cancel": {
            "patch": {
                "description": "Send create order data to order for a new product.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sales"
                ],
                "summary": "Endpoint to create a new user order",
                "parameters": [
                    {
                        "description": "The Product order data",
                        "name": "CreateOrder",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.CreateOrder"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Order response body",
                        "schema": {
                            "$ref": "#/definitions/controller.OrderResponseBody"
                        }
                    },
                    "400": {
                        "description": "API response object",
                        "schema": {
                            "$ref": "#/definitions/controller.ResponseObject"
                        }
                    }
                }
            }
        },
        "/user/order/{orderid}": {
            "get": {
                "description": "Get order data",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sales"
                ],
                "summary": "Endpoint to get an order for an individual user",
                "responses": {
                    "200": {
                        "description": "Success data. Check response body for data containing business data and all product array",
                        "schema": {
                            "$ref": "#/definitions/controller.OrderResponseBody"
                        }
                    },
                    "400": {
                        "description": "API response object",
                        "schema": {
                            "$ref": "#/definitions/controller.ResponseObject"
                        }
                    }
                }
            }
        },
        "/util/category/": {
            "get": {
                "description": "Get the list of all Categories",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Public API"
                ],
                "summary": "Endpoint to get the list of all categories on the database",
                "responses": {
                    "200": {
                        "description": "Category list and sub category",
                        "schema": {
                            "$ref": "#/definitions/controller.SubCategoryList"
                        }
                    },
                    "400": {
                        "description": "Category list",
                        "schema": {
                            "$ref": "#/definitions/controller.ResponseObject"
                        }
                    }
                }
            }
        },
        "/util/industry/": {
            "get": {
                "description": "Get the list of all industries",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Public API"
                ],
                "summary": "Endpoint to get the list of all industries on the database",
                "responses": {
                    "200": {
                        "description": "Category list and sub category",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/controller.Industries"
                            }
                        }
                    },
                    "400": {
                        "description": "Category list",
                        "schema": {
                            "$ref": "#/definitions/controller.ResponseObject"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "controller.BusinessProfile": {
            "type": "object",
            "properties": {
                "business_address": {
                    "type": "string"
                },
                "business_description": {
                    "type": "string"
                },
                "business_id": {
                    "type": "string"
                },
                "business_name": {
                    "type": "string"
                },
                "business_type": {
                    "type": "string"
                },
                "cac_registration_number": {
                    "type": "string"
                },
                "core_business_functions": {
                    "type": "string"
                },
                "core_business_training": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "deleted_at": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "industry": {
                    "type": "string"
                },
                "operational_support": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                },
                "website": {
                    "type": "string"
                },
                "years_of_operation": {
                    "type": "integer"
                }
            }
        },
        "controller.BusinessRegistration": {
            "type": "object",
            "properties": {
                "business_address": {
                    "type": "string"
                },
                "business_description": {
                    "type": "string"
                },
                "business_name": {
                    "type": "string"
                },
                "business_type": {
                    "type": "string"
                },
                "cac_registration_number": {
                    "type": "string"
                },
                "core_business_functions": {
                    "type": "string"
                },
                "core_business_training": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "industry": {
                    "type": "string"
                },
                "operational_support": {
                    "type": "string"
                },
                "website": {
                    "type": "string"
                },
                "years_of_operation": {
                    "type": "integer"
                }
            }
        },
        "controller.BusinessResponse": {
            "type": "object",
            "properties": {
                "business_address": {
                    "type": "string"
                },
                "business_description": {
                    "type": "string"
                },
                "business_id": {
                    "type": "string"
                },
                "business_name": {
                    "type": "string"
                },
                "business_type": {
                    "type": "string"
                },
                "cac_registration_number": {
                    "type": "string"
                },
                "core_business_functions": {
                    "type": "string"
                },
                "core_business_training": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "industry": {
                    "type": "string"
                },
                "operational_support": {
                    "type": "string"
                },
                "products": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/controller.ProductResponseObject"
                    }
                },
                "website": {
                    "type": "string"
                },
                "years_of_operation": {
                    "type": "integer"
                }
            }
        },
        "controller.BusinessResponseObject": {
            "type": "object",
            "properties": {
                "business": {
                    "$ref": "#/definitions/controller.BusinessProfile"
                },
                "products": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/controller.ProductResponseObject"
                    }
                }
            }
        },
        "controller.Cart": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "deleted_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "product_id": {
                    "type": "string"
                },
                "quantity": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "controller.ChangePassword": {
            "type": "object",
            "properties": {
                "new_password": {
                    "type": "string"
                },
                "old_password": {
                    "type": "string"
                }
            }
        },
        "controller.CreateOrder": {
            "type": "object",
            "properties": {
                "country": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "deleted_at": {
                    "type": "string"
                },
                "delivery_instructions": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "order_id": {
                    "type": "string"
                },
                "order_quantity": {
                    "type": "integer"
                },
                "order_status": {
                    "type": "string"
                },
                "product_id": {
                    "type": "integer"
                },
                "state": {
                    "type": "string"
                },
                "street": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "controller.CreateProductOrder": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "custom_address": {
                    "type": "boolean"
                },
                "deleted_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "order_id": {
                    "type": "string"
                },
                "order_status": {
                    "type": "string"
                },
                "payment_id": {
                    "type": "string"
                },
                "products_order_details": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/controller.ProductQuantity"
                    }
                },
                "tracking_number": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "controller.DeliveryAddress": {
            "type": "object",
            "properties": {
                "country": {
                    "type": "string"
                },
                "state": {
                    "type": "string"
                },
                "street": {
                    "type": "string"
                }
            }
        },
        "controller.Industries": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "deleted_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "industry": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "controller.LoginData": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "controller.LoginObject": {
            "type": "object",
            "properties": {
                "token_string": {
                    "type": "string"
                },
                "user_data": {
                    "$ref": "#/definitions/controller.UserData"
                },
                "user_roles": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/controller.UserRole"
                    }
                }
            }
        },
        "controller.OrderResponseBody": {
            "type": "object",
            "properties": {
                "address": {
                    "$ref": "#/definitions/controller.DeliveryAddress"
                },
                "order_quantity": {
                    "type": "integer"
                },
                "product": {
                    "$ref": "#/definitions/controller.ProductResponseObject"
                },
                "user": {
                    "$ref": "#/definitions/controller.UserData"
                }
            }
        },
        "controller.Pay": {
            "type": "object",
            "properties": {
                "business_id": {
                    "type": "string"
                },
                "cost": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "deleted_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "order_id": {
                    "type": "string"
                },
                "payment_id": {
                    "type": "string"
                },
                "product_id": {
                    "type": "string"
                },
                "transaction_id": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "controller.ProductDiscount": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "deleted_at": {
                    "type": "string"
                },
                "discountPercentage": {
                    "type": "number"
                },
                "id": {
                    "type": "integer"
                },
                "product_id": {
                    "type": "integer"
                },
                "product_name": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "controller.ProductImage": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "deleted_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "image_url": {
                    "type": "string"
                },
                "product_id": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "controller.ProductQuantity": {
            "type": "object",
            "properties": {
                "product_id": {
                    "type": "string"
                },
                "quantity": {
                    "type": "integer"
                }
            }
        },
        "controller.ProductResponseObject": {
            "type": "object",
            "properties": {
                "discount": {
                    "$ref": "#/definitions/controller.ProductDiscount"
                },
                "industry": {
                    "type": "string"
                },
                "item_left": {
                    "type": "integer"
                },
                "price": {
                    "type": "string"
                },
                "product_description": {
                    "type": "string"
                },
                "product_id": {
                    "type": "string"
                },
                "product_images": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/controller.ProductImage"
                    }
                },
                "product_name": {
                    "type": "string"
                },
                "ratings": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/controller.Rating"
                    }
                },
                "section": {
                    "type": "string"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/controller.Tags"
                    }
                }
            }
        },
        "controller.Products": {
            "type": "object",
            "properties": {
                "business_id": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "deleted_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "industry": {
                    "type": "string"
                },
                "photo": {
                    "type": "string"
                },
                "price": {
                    "type": "string"
                },
                "product_description": {
                    "type": "string"
                },
                "product_id": {
                    "type": "string"
                },
                "product_name": {
                    "type": "string"
                },
                "stock_quantity": {
                    "type": "integer"
                },
                "tags": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "controller.Rating": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "deleted_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "product_id": {
                    "type": "string"
                },
                "product_name": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_comments": {
                    "type": "string"
                },
                "user_name": {
                    "type": "string"
                },
                "user_rating": {
                    "type": "integer"
                }
            }
        },
        "controller.RegistrationData": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "full_name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "controller.RegistrationObject": {
            "type": "object",
            "properties": {
                "token_string": {
                    "type": "string"
                },
                "user_data": {
                    "$ref": "#/definitions/controller.UserData"
                },
                "user_role": {
                    "$ref": "#/definitions/controller.UserRole"
                }
            }
        },
        "controller.ResponseObject": {
            "type": "object",
            "properties": {
                "body": {
                    "type": "object"
                },
                "code": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "controller.SearchResult": {
            "type": "object",
            "properties": {
                "business_array": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/controller.BusinessResponseObject"
                    }
                },
                "business_match": {
                    "type": "boolean"
                },
                "no_match": {
                    "type": "boolean"
                },
                "product_match": {
                    "type": "boolean"
                },
                "products": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/controller.ProductResponseObject"
                    }
                }
            }
        },
        "controller.SocialMedia": {
            "type": "object",
            "properties": {
                "facebook": {
                    "type": "string"
                },
                "instagram": {
                    "type": "string"
                },
                "twitter": {
                    "type": "string"
                }
            }
        },
        "controller.SubCategoryList": {
            "type": "object",
            "properties": {
                "category": {
                    "type": "string"
                },
                "subcategories": {
                    "type": "array",
                    "items": {
                        "type": "object"
                    }
                }
            }
        },
        "controller.Tags": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "deleted_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "tag": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "controller.UserData": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "deleted_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "display_picture": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "full_name": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "phone_number": {
                    "type": "string"
                },
                "socialMedia": {
                    "$ref": "#/definitions/controller.SocialMedia"
                },
                "updated_at": {
                    "type": "string"
                },
                "uuid": {
                    "type": "string"
                }
            }
        },
        "controller.UserRole": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "deleted_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "role": {
                    "type": "string"
                },
                "role_code": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "uuid": {
                    "type": "string"
                }
            }
        },
        "controller.VerifyRegistration": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "verification_code": {
                    "type": "string"
                }
            }
        },
        "controller.VerifyToken": {
            "type": "object",
            "properties": {
                "token_string": {
                    "type": "string"
                },
                "validity": {
                    "type": "boolean"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        },
        "BasicAuth": {
            "type": "basic"
        },
        "OAuth2AccessCode": {
            "type": "oauth2",
            "flow": "accessCode",
            "authorizationUrl": "https://example.com/oauth/authorize",
            "tokenUrl": "https://example.com/oauth/token",
            "scopes": {
                "admin": " Grants read and write access to administrative information"
            }
        },
        "OAuth2Application": {
            "type": "oauth2",
            "flow": "application",
            "tokenUrl": "https://example.com/oauth/token",
            "scopes": {
                "admin": " Grants read and write access to administrative information",
                "write": " Grants write access"
            }
        },
        "OAuth2Implicit": {
            "type": "oauth2",
            "flow": "implicit",
            "authorizationUrl": "https://example.com/oauth/authorize",
            "scopes": {
                "admin": " Grants read and write access to administrative information",
                "write": " Grants write access"
            }
        },
        "OAuth2Password": {
            "type": "oauth2",
            "flow": "password",
            "tokenUrl": "https://example.com/oauth/token",
            "scopes": {
                "admin": " Grants read and write access to administrative information",
                "read": " Grants read access",
                "write": " Grants write access"
            }
        }
    },
    "x-extension-openapi": {
        "example": "value on a json format"
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0",
	Host:        "localhost:8112",
	BasePath:    "/api/v1",
	Schemes:     []string{},
	Title:       "Barafiri Backend API documentation",
	Description: "This is the official data model for BARAFIRI API documentation.\nBarafiri documentation port: 8112\napicore port: 7002\nmailer port: 7006\nsales service: 7003\npublic endpoints: 7005 (This includes CART, PUBLIC API, PUBLIC SEARCH)\nproducts service: 7007",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
